import os
import shlex
import subprocess
from flask_login import current_user

from EpiMap import app



def create_user_folder(upload_folder='', userID=''):
    """
    Create user directory as script workspace
    The user folder's name is generated by concatenating user ip and system time

    Args:
        userID (string): user folder name
        upload_folder (string): the ROOT folder of upload files

    Returns:
        Full path of user directory
    """

    user_dir = os.path.join(upload_folder, '_'.join([userID, current_user.username]))
    # create directory
    cmd_args = shlex.split('mkdir ' + user_dir)
    print(cmd_args)
    subprocess.Popen(cmd_args).wait()

    return user_dir


def call_scripts(methods, user_dir='', data_file_x='', data_file_y=''):
    """
    Call methods' scripts from python, and don't wait the processing.

    Args:
        methods (): checked methods
        user_dir (string): user directory
        data_file (string): uploaded data file
    """
    with open(os.path.join(user_dir, 'stdout.log'), 'w') as stdout_log, \
            open(os.path.join(user_dir, 'stderr.log'), 'w') as stderr_log:
        for method in methods:
            if method == 'EBEN':
                subprocess.Popen(['script', app.config['EBEN_SCRIPT'], user_dir, data_file_x],
                                 stdout=stdout_log,
                                 stderr=stderr_log)

            if method == 'LASSO':
                pass

            if method == 'meQTL':
                pass
