"""status

Revision ID: db9b2844cfb2
Revises: f79ce9a0868a
Create Date: 2018-06-13 22:44:29.720695

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'db9b2844cfb2'
down_revision = 'f79ce9a0868a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job") as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=False))
        batch_op.drop_column('state')

    with op.batch_alter_table("model") as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=False))
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('state', sa.INTEGER(), nullable=False))
    op.drop_column('model', 'status')
    op.add_column('job', sa.Column('state', sa.INTEGER(), nullable=False))
    op.drop_column('job', 'status')
    # ### end Alembic commands ###
