"""is_shared

Revision ID: e9953c903369
Revises: 585e15ad67fb
Create Date: 2018-06-13 17:35:18.529241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9953c903369'
down_revision = '585e15ad67fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('is_shared', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'is_shared')
    # ### end Alembic commands ###
